dbt_trino:
  outputs:
    trino_output:
      type: trino
      method: none
      user: dbt
      database: iceberg
      host: trino-coordinator
      port: 8080
      schema: silver
      threads: 1
  target: trino_output
